### ISSUE TITLE
Creating lamba layers in typescript

### ISSUE THREAD

**Issue by Jkap7788** [SnappyTutorials/aws-sam-webpack-plugin#14]
Hi, thank you so much for creating this plugin!

I'm very new to typescript and sam in general but was wondering how I would go about creating a lambda layer written in typescript.

For example, I want to be able to share code between many different lambda functions (spread across multiple sam templates).

Some advice on how to do this would be highly appreciated!

Thanks

**Comment by Jkap7788** [comment]
Additionally, would lambda layers be the best approach to share code? Perhaps using webpack to import common code would work?

**Comment by buggy** [comment]
My preference is for using private npm packages for shared code.

**Comment by Hasan-git** [comment]
Try to copy layers folder

webpack.config.js

`const CopyPlugin = require('copy-webpack-plugin');`

>   // Add the AWS SAM Webpack plugin
>   plugins: [
>     awsSamPlugin,
> 
>     // @ Copy layers to build dir
>     new CopyPlugin([
>       { from: 'layers', to: 'layers' },
>     ]),
>   ]
