### ISSUE TITLE
webpack dll plugin support?

### ISSUE THREAD

**Issue by dlydiard** [SnappyTutorials/aws-sam-webpack-plugin#18]
are there any plans for this plugin to support webpack-dll-plugin out of the box? or is the recommended approach to use a plugin like copy-webpack-plugin to copy the "vendor.dll.js" file to each lambda function's .aws-sam/build/[function name] folder?

**Comment by buggy** [comment]
I'm not familiar with the webpack-dll-plugin but my best guess is that it's incompatible.

**Comment by dlydiard** [comment]
webpack dll plugin pre-compiles node_modules (for example) into a single vendor-dll.js file, then webpack will reference this dll for dependencies. This is very useful for drastically faster compile times since only the lambda functions need to be compiled (one time compile for dll) vs. lambda + node_modules.

The problem is, the vendor-dll.js file needs to copied to each lambda folder in the .aws-sam/build[function name] folder, which your plugin creates and is aware of.  I don't  think copy-webpack-plugin is smart enough to do this correctly.

perhaps making a aws-sam-webpack-dll-plugin plugin project based on your plugin would be best?
 
https://webpack.js.org/plugins/dll-plugin/

**Comment by buggy** [comment]
If you just need to copy a file into a different location then the copy plugin should work.

**Comment by dlydiard** [comment]
i got this working with an 'afterEmit' webpack hook. 'copy webpack plugin' did not work because it tries to copy before the dll is built.

example webpack.config.js: 

```
const AwsSamPlugin = require('aws-sam-webpack-plugin');

plugins: [
{
    apply: (compiler) => {
        compiler.hooks.afterEmit.tap('CopyAfterEmitPlugin', compilation => {
          Object.keys(awsSamPlugin.entry()).forEach(entry => {
            // merge dll here e.g. 
            // merge /.aws-sam/build/vendor.dll.js => '/.aws-sam/build' + entry + '/app.js'
         })
      });
    }
 }
```
