### ISSUE TITLE
Is it possible to hot-reload `template.yaml`?

### ISSUE THREAD

**Issue by vadzim** [SnappyTutorials/aws-sam-webpack-plugin#21]
Hot reloading source files with `aws-sam-webpack-plugin` is such a wonderfull and convenient thing that it's hard to remember why things stopped to work after adding another lambda to `template.yaml` :)

So the question is is it really possible to hot-reload `template.yaml` when it's been changed?

**Comment by vadzim-revolist** [comment]
I think this is a relative thing: https://github.com/webpack/webpack-cli/issues/15

**Comment by buggy** [comment]
You might be able to use nodemon to restart webpack but I can't see another solution. The only time the entry points can be set in the webpack.config.js is when webpack loads it. If they provide another way to set them then I'm happy to revisit this request.

**Comment by buggy** [comment]
After re-reading the Webpack docs I'm going to change the recommended `webpack.config.js` from `entry: awsSamPlugin.entry()` to `entry: () => awsSamPlugin.entry()` which will cause it to reload the entry points each time it builds. It will still only build once a source file is changed (not `template.yaml`) but you'll always be building from the most recently saved `template.yaml`.

**Comment by vadzim** [comment]
Wow. I missed that entry-function feature in webpack. Thanks.

Yeah, I'm already using nodemon.

I know that webpack plugins can add dependencies to watch into webpack while building projects.
May be `awsSamPlugin` could do that for `template.yaml`?
Then it wouldn't need to use `nodemon`.
This will allow to escape repeating file names and is gonna be less error-prone.

**Comment by vadzim** [comment]
P.S. There is also one trick, if `awsSamPlugin.entry` is not a method of a class, but just a field with a function, then it can be used like `entry: awsSamPlugin.entry`, without brackets.

**Comment by buggy** [comment]
I'm not planning to add further support for hot reloading based on the `template.yaml` changing.
