### ISSUE TITLE
Fail early if lambda source isn't available

### ISSUE THREAD

**Issue by vadzim** [SnappyTutorials/aws-sam-webpack-plugin#22]
If there is an mistype in `template.yaml` and the function referenced there does not exist then plugin just silently does nothing.

I think it could be useful to emit errors in such a case.

**Comment by buggy** [comment]
@vadzim Can you provide an example of this?

**Comment by vadzim** [comment]
Oh.. I thought it's by design..
Ok, I'll try to extract minimal example

**Comment by vadzim** [comment]
https://github.com/vadzim/AwsSamTestData

`template.yaml` contains a reference to non-existing file `Z.js`

### actions:
- run `npm run build`

### actual behaviour:
- command runs successfully and show neither erros nor warnings. It builds one lambda function which has a valid reference to `X.js`

### expected behaviour:
- command shows some info about wrong entry in `template.yaml`

In the first commit 21e78b82bc2c744b57fddea71b378bf3b3045249 `template.yaml` contains two valid references to `X.js` and `Y.js` and build them both successfully.

**Comment by vadzim** [comment]
Here https://github.com/SnappyTutorials/aws-sam-webpack-plugin/blob/570602bebf8d25777dec647c551175ed5c8bec8f/src/index.ts#L97 the code check if the file with extension `.js` or `.ts` exists and creates an entry for webpack only if that file exists. The code just does nothing if the file does not exist. It neither adds some entry nor reports any error.

**Comment by vadzim** [comment]
Webpack allows to specify entries without extensions and also specify an option how to resolve files without extensions:
```js
  entry: {
    X: './src/X',
    Y: './src/Y',
  },
  resolve: {
    extensions: ['.ts', '.js'],
  },
```
So I guess there is enough to just generate entry without either `.ts` or `.js` extension and let webpack do its work.
In such case webpack will be responsive for error handling if entry is absent.

There is an example which checks that webpack can handle entries without extensions https://github.com/vadzim/AwsSamTestData/tree/WebpackEntryWithoutExtension

**Comment by buggy** [comment]
Great work @vadzim
