### ISSUE TITLE
Feature request: Template location

### ISSUE THREAD

**Issue by daveykane** [SnappyTutorials/aws-sam-webpack-plugin#6]
It would be great if you could pass in as an option the location of the template, rather than it currently requiring template.yaml in the root. 

If no option is passed it would still default to a root template.yaml file but otherwise it would use the passed template path. This would also allow you to instantiate multiple instances of the plugin, one per template if you happened to have more than one template in a project but all using a single webpack config.

**Comment by buggy** [comment]
@daveykane I think I have a similar problem. If I understand you correctly then I could solve this by adding `projectDirs` to the plugin options with a default value `["."]`. It would treat each folder in `projectDirs` as its own SAM project expecting a `template.yaml` with the config and creating a `.aws-sam` for the output.

Example:

If I set `projectDirs: ["project1", "project2"]` then it build project1 using `project1/template.yaml` with the output going to `project1/.aws-build` and project2 using `project2/template.yaml` with the output going to `project2/.aws-build`. You would still need to run `sam package` and `sam deploy` in each of the project folders.

If I don't set `projectsDirs` then it defaults to `["."]` so it looks for `template.yaml` in the current folder with output going to `.aws-sam` in the same folder.

Does this sound correct?

**Comment by daveykane** [comment]
@buggy yes that sounds like it would work to me, good shout.

I saw you also made an update for the next release to skip functions using inline code, thanks for that and thanks for the great work on the plugin so far.

**Comment by buggy** [comment]
I've got a couple of other things I want to add and I'll try to get 0.4.0 released in the next few days.

**Comment by vadzim** [comment]
Hi @buggy 
Thanks for such plugin, it's saved me really much time.

I just wonder what's the reason that name of `template.yaml` is hardcoded? As I know sam allows to specify the name of template in command line.

**Comment by buggy** [comment]
> I just wonder what's the reason that name of template.yaml is hardcoded?

It's just the way I built it. I picked `template.yaml` and `template.yml` because they're the two defaults that SAM uses. You're the first person to ask for it to support other names.

**Comment by vadzim** [comment]
Yes, `template.yaml` is used widely. I've just noted that compatibility with running `sam build` is mentioned as one of project goals, and `sam` already has an option to specify path to template and that path can be arbitrary file name.
`sam` is rather often used tool and this plugin is still gaining its poplularity, so I believe I'm the first one, but not the last))

**Comment by buggy** [comment]
I've pushed experimental support for building multiple projects to the develop branch. Once I run some more tests I'll release version 0.5.0 with it.

@vadzim you can use the `projects` option to have different template names.
