### ISSUE TITLE
Why is @types/aws-lambda dependency required as devDependency?

### ISSUE THREAD

**Issue by trivikr** [SnappyTutorials/aws-sam-webpack-plugin#9]
Thank you @buggy for creating this helpful plugin.
We're currently using it in [aws-samples/aws-sdk-js-v3-workshop](https://github.com/aws-samples/aws-sdk-js-v3-workshop)

Question: Why is `@types/aws-lambda` devDependency required as mentioned in tutorials https://github.com/SnappyTutorials/aws-sam-webpack-plugin/blob/master/README.md?
I built my workshop code without that dependency, and it worked fine.

The only place where `aws-lambda` is mentioned in this repo is in README.
Search link: https://github.com/SnappyTutorials/aws-sam-webpack-plugin/search?q=aws-lambda&unscoped_q=aws-lambda

**Comment by trivikr** [comment]
The PR which removed @types/aws-lambda dependency https://github.com/aws-samples/aws-sdk-js-v3-workshop/pull/63

**Comment by buggy** [comment]
@trivikr That's awesome. `@types/aws-lambda` provides the type definitions for Lambda events. You don't technically need it but if you're using TypeScript with the V2 SDK then you'll want it. I'm not sure if the V3 SDK added these.

I'm finishing up version 0.4.0 of the plugin now and I'll fix the documentation as part of that.

**Comment by trivikr** [comment]
> You don't technically need it but if you're using TypeScript with the V2 SDK then you'll want it

I'm using TypeScript with v2 SDK, but I'm not using [AWS.Lambda](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html) in my code. The v2 SDK is written in JavaScript, but we ship types along with the code. 

> I'm not sure if the V3 SDK added these.

The v3 SDK is written in TypeScript, and gets in-built types with all the code.

> I'm finishing up version 0.4.0 of the plugin now and I'll fix the documentation as part of that.

Thanks! That would be very helpful.

**Comment by buggy** [comment]
@trivikr The last time I checked the AWS SDK included the type definitions for the API's but not the events/context passed to Lambda which is what the `@types/aws-lambda` package provides. Do you have a reference to these from the AWS-SDK? I'd love to switch it in my code if you do.

**Comment by trivikr** [comment]
Example lambda which I've written in the workshop: https://github.com/aws-samples/aws-sdk-js-v3-workshop/blob/master/Exercise1/backend/src/create.ts

In VSCode editor, it shows `event: any` irrespective of whether `@types/aws-lambda` is present as a devDependency
![event](https://user-images.githubusercontent.com/16024985/67723238-a8920d80-f998-11e9-9cf3-61bfc58c7570.png)

Is some code change required to get TypeScript definitions for event/context?

**Comment by trivikr** [comment]
I've to explicitly add Event type in lambda definition as follows:
* For example [create.ts](https://github.com/aws-samples/aws-sdk-js-v3-workshop/blob/4e19f7dd8c88245d360b467b836b6d9f56873926/Exercise1/backend/src/create.ts#L5), the event is APIGatewayProxyEvent
![APIGatewayProxyEvent](https://user-images.githubusercontent.com/16024985/67724136-4edf1280-f99b-11e9-84b9-1c34f00c77b3.png)
* The type definition is defined in `@types/aws-lambda`
![APIGatewayProxyEvent-definition](https://user-images.githubusercontent.com/16024985/67724159-5e5e5b80-f99b-11e9-84d0-0de97268e8c7.png)

I wasn't aware of this usage of `@types/aws-lambda`
This issue can be resolved, or can be used for improved documentation in this repository.

Links:
* Existing code on GitHub which use APIGatewayProxyEvent type while writing lambda https://github.com/search?q=APIGatewayProxyEvent&type=Code
* StackOverflow https://stackoverflow.com/questions/53976371
